#!/bin/bash

# SPDX-FileCopyrightText: 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@kicksecure.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -x
set -e

sudo apt-get install qemu-utils

## user: root
## password: changeme

## hints:
## drop -nographic
## press "E" in grub boot menu
## remove: quiet
## add: verbose debug rd.debug

qemu-system-x86_64 \
    -nographic \
    -m 1024 \
    -drive format=raw,file=/home/user/grml-debootstraptestbin/test.img
