#!/bin/bash

# SPDX-FileCopyrightText: 2023 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@kicksecure.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -x
set -e

qemu-system-x86_64 \
    -nographic \
    -m 1024 \
    -device virtio-rng-pci \
    -boot d \
    -cdrom ~/grml-debootstraptestbin/output.iso
