#!/bin/bash

set -x
set -e

## We might get away with --no-install-recommends, fewer packages.
sudo apt-get install qemu-system-arm qemu-system-aarch64 qemu-efi-aarch64 qemu-utils

## user: user
## password: changeme

qemu-system-aarch64 \
    -M virt \
    -cpu cortex-a57 \
    -m 1024 \
    -bios /usr/share/qemu-efi-aarch64/QEMU_EFI.fd \
    -drive format=raw,file=/home/user/grml-debootstraptestbin/test.img \
    -nographic
