#!/bin/bash

# SPDX-FileCopyrightText: 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@kicksecure.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

## Initial fork.
## cp /usr/lib/live/build/binary_grub-efi ./binary_grub-efi

set -x
set -e
set -o nounset
set -o allexport

LIVE_BUILD=/usr/lib/live/build/scripts
_COLOR=""
## TODO
LB_ARCHITECTURE=amd64
LB_PARENT_DISTRIBUTION=sid
LB_APT_HTTP_PROXY=""
LB_LINUX_FLAVOURS=""
LB_BOOTLOADER_BIOS=grub-pc
LB_BOOTLOADER_EFI=grub-efi
LB_CONFIG=""
LB_BOOTLOADERS="grub-efi grub-pc"
LB_DEBIAN_INSTALLER_PRESEEDFILE="/preseed.cfg"
LB_BOOTAPPEND_INSTALL=""
LB_BOOTSTRAP_QEMU_ARCHITECTURES=""
CONFIG_VALIDATED=true
_LB_PACKAGES=""
http_proxy=""
no_proxy=""
LB_BUILD_WITH_CHROOT=false
LB_UEFI_SECURE_BOOT=enable
## set by image-to-iso
ISO_TMP_DIR="$ISO_TMP_DIR"
BINARY_FOLDER="$BINARY_FOLDER"
ISO_IMAGE_FILE="$ISO_IMAGE_FILE"

LB_IMAGE_TYPE=iso-hybrid
_QUIET=""
_VERBOSE="true"
LB_ISO_APPLICATION=none
LB_ISO_VOLUME=cdlabel
LB_ISO_PREPARER=preparer
LB_ISO_PUBLISHER=publisher

sh -xveu ./binary_iso
