#!/bin/bash

VMNAME=test
USERNAME=user
VMSIZE=2G

create_img() {
   trap "error_handler_int_whonix_image" ERR INT TERM

   sudo -u $USERNAME mkdir -p "/home/user/grml-debootstraptestbin"

   grml-debootstrap \
      --arch i386 \
      --filesystem ext4 \
      --force \
      --hostname host \
      --mirror http://ftp.us.debian.org/debian \
      --keep_src_list \
      --password changeme \
      --release wheezy \
      --verbose \
      --vmfile \
      --vmsize "$VMSIZE" \
      --config "./grml_config" \
      --packages "./${VMNAME}_packages" \
      --target "/home/user/grml-debootstraptestbin/$VMNAME.img"
}

create_img
