#!/bin/bash

## Must be run with root (sudo)!

set -x
set -e

VMSIZE=2G

create_img() {
   sudo -u "$SUDO_USER" mkdir -p "/home/$SUDO_USER/grml-debootstraptestbin"

   export DEBUG="true"

   #export KERNEL="linux-image-amd64"

   export DEBOOTSTRAP=mmdebstrap
   export http_proxy=http://127.0.0.1:3142

   bash -x \
      grml-debootstrap \
         --arch arm64 \
         --filesystem ext4 \
         --force \
         --hostname host \
         --mirror http://HTTPS///deb.debian.org/debian \
         --keep_src_list \
         --password changeme \
         --release bookworm \
         --verbose \
         --vmfile \
         --vmsize "$VMSIZE" \
         --target "/home/$SUDO_USER/grml-debootstraptestbin/test.img"

   chown --recursive user:user /home/$SUDO_USER/grml-debootstraptestbin
}

create_img
