#!/bin/sh

# SPDX-FileCopyrightText: 2023 - 2023 ENCRYPTED SUPPORT LP <adrelanos@kicksecure.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

Require_stagefiles() {
  true noop
}

Stagefile_name() {
  true noop
}

Install_packages() {
  true noop
}

Restore_package_cache() {
  true noop
}

Create_stagefile() {
  true noop
}

Remove_packages() {
  true noop
}

Save_package_cache() {
  true noop
}
