#!/bin/bash

set -x
set -e

VMNAME=test

mount_img() {
   sync
   kpartx -av "/home/$SUDO_USER/debootstraptestbin/$VMNAME.img"
   sync
   mkdir -p "/home/$SUDO_USER/debootstraptestbin/mounted"
   sync
   mount "/dev/mapper/loop0p1 /home/$SUDO_USER/debootstraptestbin/mounted"
   sync
}

mount_img
