#!/bin/bash

set -x
set -e

VMNAME="test"

unmount_img() {
   sync
   umount "/home/$SUDO_USER/debootstraptestbin/"
   sync
   kpartx -d "/home/$SUDO_USER/debootstraptestbin/$VMNAME.img"
   sync
}

unmount_img
