#!/bin/bash

# SPDX-FileCopyrightText: 2013 - 2023 ENCRYPTED SUPPORT LP <adrelanos@kicksecure.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -x
set -e

VMNAME="test"

unmount_img() {
   sync
   umount "/home/$SUDO_USER/debootstraptestbin/"
   sync
   kpartx -d "/home/$SUDO_USER/debootstraptestbin/$VMNAME.img"
   sync
}

unmount_img
